spring:
  application:
    name: Leave Management
  datasource:
    url: jdbc:postgresql://localhost:5432/leave-management
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      firstName: Admin
    filter:
      create: All tasks